### PR TITLE
MADS: Switch from libblast to common/dcl imported from main project

### PR DESCRIPTION
**Pull request by phcoder**

### CODE REVIEW

**Review by aquadran — COMMENTED** [review]
please fix commit message related dcl

**Comment by phcoder** [comment]
> please fix commit message related dcl

Done

**Comment by lephilousophe** [comment]
It looks like the PR got SAGA PR added to it.

**Comment by phcoder** [comment]
> It looks like the PR got SAGA PR added to it.

Fixed

**Comment by sev-** [comment]
Looks good, thank you!

**Pull request merged**
