### PR TITLE
HADESCH: Publish my tool for extracting pod files

### PR DESCRIPTION
**Pull request by phcoder**
This is a basic uncompressed archive used by Hades' Challenge.

### CODE REVIEW

**Comment by raziel-** [comment]
Heh, thanks a lot for adding it to the AmigaOS part as well, saves me one PR :-)

**Comment by sev-** [comment]
Could you please rename it to `extract_hadessch`, just in line with the rest of the tools?

**Comment by phcoder** [comment]
> Could you please rename it to `extract_hadesch`, just in line with the rest of the tools?

Done

**Comment by sev-** [comment]
Thanks!

**Pull request merged**
