### PR TITLE
Fix descumm syntax errors

### PR DESCRIPTION
**Pull request by osiegmar**
Fixed some syntax errors (please see individual commit messages for details).

### CODE REVIEW

**Comment by sev-** [comment]
This PR does not conform with our commit guidelines. https://wiki.scummvm.org/index.php?title=Commit_Guidelines

Please add "TOOLS: " in front of every commit log message.

**Comment by osiegmar** [comment]
I just added the requested prefix. Now the Codacy analysis seems to fail but Codacy itself says "Up to standards. A positive pull request.". The only way to 'retry' seems to be to modify the PR again.

**Comment by osiegmar** [comment]
Yep, now it works.

@sev- I'd suggest to create a Github [CONTRIBUTING file](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors) that contains a link the the commit guidelines (and other related information).

**Comment by sev-** [comment]
Codacy is useless, we forgot to remove it.

Thank you for the CONTRIBUTING file suggestion. We will add it.

And thank you for the PR, merging it now.

**Comment by Die4Ever** [comment]
> Codacy is useless, we forgot to remove it.
> 
> Thank you for the CONTRIBUTING file suggestion. We will add it.
> 
> And thank you for the PR, merging it now.

Honestly I like some of the suggestions that Codacy makes, idk if it should be removed

**Pull request merged**
