### PR TITLE
CONFIGURE: (AMIGAOS) Fix undefined references

### PR DESCRIPTION
**Pull request by raziel-**
AmigaOS recently got an updated libFLAC (1.4.2) which was compiled with -fstack-protector (thank you @sev-  for clearing that up)

Compiling scummvm-tools now lead to numerous undefined references to __stack_chk_fail. Hence using -lssp which fixes the errors and compiles working binaries again.

I don't know if this is the right approach or if there would be a better solution, so please advise

Thank you

### CODE REVIEW

**Comment by sev-** [comment]
This is not the right approach.

First, there is already the `case` over `_host` starting from like 577.

Second, you are NOT providing library, but flags, thus, use LDFLAGS instead of LIBS

**Comment by raziel-** [comment]
So, yes, i don't know what to do.

Someone else may look at this problem and immediately know how to work aorund it...i don't.

I need to add -lssp at configure level *after* the FLAC LIBS (-LFLAC -logg), so FLAC gets recognized and later properly linked in.

I have the same problem in scummvm btw, but there configure is much more "strict" as-in it rules out FLAC during configure completely (due to the missing -lssp flag) and simply doesn't compile it in et al.
Of course i'm left without FLAC support in the binary then.

*any* help *very* appreciated

Thank you very much in advance

**Comment by raziel-** [comment]
@lotharsm 

Thank you, I'll try that when I get back home.

Though I fear that it will add -lssp in front of FLAC_LIBS (which will break FLAC recognition again and fail to add it as supported) which gets checked later, as far as I can see.

I need to check it locally first though, of course

**Comment by ccawley2011** [comment]
Do you have pkg-config available when building natively on AmigaOS? If so, a solution might be to use that to list the required libraries instead of hard-coding them, similarly to what we do for a few other libraries.

**Comment by raziel-** [comment]
@ccawley2011

I do, but it's a rather old version.
Can't remember right now, but I'll check.

What would be the command to use/try?
Thank you

**Comment by ccawley2011** [comment]
> What would be the command to use/try? Thank you

You might want to try:
```
pkg-config --libs flac
```
which returns `-lFLAC` on Linux, or:
```
pkg-config --static --libs flac
```
which returns `-lFLAC -lm -logg` on Linux.

**Comment by raziel-** [comment]
@ccawley2011 

I'll try, thank you very much.

I know that --static doesn't work with my version of pkg-config (as i said, pretty old), since i already get a warning with freetype2

**Comment by raziel-** [comment]
@ccawley2011

pkg-config --version
0.15.0

i get this:

pkg-config --libs flac
-L/SDK/local/newlib/lib -lFLAC

as written above the --static flac isn't supported and triggers a warning
 --static: unknown option

Both scummvm-tools and scummvm doesn't seem to correctly use/add them through pkg-config though, because even if i add -lssp to flac.pc it isn't used.

What now?

Thank you

**Comment by lephilousophe** [comment]
Sadly, even Libs.Private is incorrect in the pkg-config file and misses `-lssp`. 
Another solution would be to compile ScummVM with `-fstack-protector` to force use of libssp

**Comment by raziel-** [comment]
@lephilousophe 

/me hugs @lephilousophe

That did it, a general workaround for all future dependencies that might have been compiled with stack protection, exactly what i was looking for :-)

Thank you

**Comment by raziel-** [comment]
I still get this error on linking, while all other errors are gone.

I don't really know if it's related as it may have snuck in between the broken builds and i simple didn't see it
Development:Coding/SDK/gcc/ppc-amigaos/bin/ld: Dwarf Error: found dwarf version '5', this reader only handles version 2, 3 and 4 information.
encode_dxa.o: In function `EncodeDXA::read_png_file(char const*, unsigned char*&, unsigned char*&, int&, int&)':
encode_dxa.cpp:(.text+0x3464): undefined reference to `png_read_image'

**Comment by raziel-** [comment]
Disregard my last comment, another case of broken local dependy...fixed and tools build fine with the change

**Pull request merged**
