### PR TITLE
AMIGAOS: Automate install process

### PR DESCRIPTION
**Pull request by raziel-**
This is to automate the install process when comiling with amigaosdist.

Please can someone be so kind to also upload the icon files to /gui/media/?
Just get rid of the .png suffix.
The should be called
scummvm-tools.drawer.info
and
ScummVM-Tools.info

Thanks a lot

ScummVM-Tools info
scummvm-tools_drawer info

### CODE REVIEW

**Comment by sev-** [comment]
There are conflicts in configure, this has to be rebased.

**Comment by sev-** [comment]
Where exactly would you like uploading those Workbench pictures?

**Comment by sev-** [comment]
I added the icons

**Comment by raziel-** [comment]
@sev-

Thank you, icon destination is fine
I dont know how to rebase it from the website.
Could you do it?
Otherwise I simply close and reopen this with one or two changes?

Could you also please rename the uploaded Icons to
(All lower-case)
scummvm-tools.info
and
scummvm-tools_drawer.info

Thanks you very much

**Comment by sev-** [comment]
I cannot do the rebase, thus, via Web, this should be probably just reopened.

**Comment by raziel-** [comment]
@sev

Done. #28

Hope, I didn't break anything

**Pull request closed without merging**
